[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -p no:launch_testing
    -p no:launch_testing_ros
    -p no:launch-testing-ros
    -p no:ament_copyright
    -p no:ament_flake8
    -p no:ament_pep257
    -p no:ament_xmllint
    -p no:ament_lint
