# Runs at build time (cmake -P), so the recorded git SHA is the one the
# binary was actually built from, not the one present at configure time.
# Inputs: SOURCE_DIR, OUTPUT, BUILD_TYPE, COMPILER, VERSION.
execute_process(COMMAND git -C "${SOURCE_DIR}" rev-parse HEAD
                OUTPUT_VARIABLE _sha OUTPUT_STRIP_TRAILING_WHITESPACE
                RESULT_VARIABLE _rc ERROR_QUIET)
if(NOT _rc EQUAL 0 OR _sha STREQUAL "")
  set(_sha "unknown")
endif()
execute_process(COMMAND git -C "${SOURCE_DIR}" status --porcelain --untracked-files=no
                OUTPUT_VARIABLE _dirty OUTPUT_STRIP_TRAILING_WHITESPACE
                RESULT_VARIABLE _rc2 ERROR_QUIET)
if(_rc2 EQUAL 0 AND NOT _dirty STREQUAL "")
  set(_dirty_flag "true")
else()
  set(_dirty_flag "false")
endif()
set(_content "// Generated by cmake/BuildInfo.cmake. Do not edit.
#pragma once
namespace blackboxrs::build_info {
inline constexpr const char* kGitSha = \"${_sha}\";
inline constexpr bool kGitDirty = ${_dirty_flag};
inline constexpr const char* kBuildType = \"${BUILD_TYPE}\";
inline constexpr const char* kCompiler = \"${COMPILER}\";
inline constexpr const char* kVersion = \"${VERSION}\";
}  // namespace blackboxrs::build_info
")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" _old)
else()
  set(_old "")
endif()
if(NOT _old STREQUAL _content)
  file(WRITE "${OUTPUT}" "${_content}")
endif()
